# Generated by Django 2.2 on 2019-06-09 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 9, 22, 45, 3, 121976), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 9, 22, 45, 3, 121976), verbose_name='date published'),
        ),
    ]
