# Generated by Django 2.2 on 2019-06-09 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190609_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='news_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 9, 22, 52, 15, 145402), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 9, 22, 52, 15, 145402), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='TournamentSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_series', models.CharField(max_length=200)),
                ('series_summary', models.CharField(max_length=200)),
                ('tournament_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TournamentCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_title', models.CharField(max_length=200)),
                ('tournament_content', models.TextField()),
                ('tournament_published', models.DateTimeField(default=datetime.datetime(2019, 6, 9, 22, 52, 15, 145402), verbose_name='date published')),
                ('tournament_slug', models.CharField(default=1, max_length=200)),
                ('tournament_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TournamentSeries', verbose_name='Series')),
            ],
        ),
    ]
