# Generated by Django 2.2 on 2019-09-15 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190609_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 13, 42, 22, 824860), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 13, 42, 22, 824860), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 13, 42, 22, 824860), verbose_name='date published'),
        ),
    ]
