# Generated by Django 2.2 on 2019-09-15 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190915_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 13, 47, 43, 375662), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 13, 47, 43, 375662), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 13, 47, 43, 375662), verbose_name='date published'),
        ),
    ]
