# Generated by Django 2.2 on 2019-09-15 02:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190915_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 14, 2, 54, 786194), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='21kyu', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 14, 2, 54, 786194), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 14, 2, 54, 786194), verbose_name='date published'),
        ),
    ]
